Repository planetarium/arena-win-rate-calculator, pull requests merged in 2024-03, with the labels that each got.

#19 PDX-394: apply reveal rate design and etc
  package.json
  src/App.tsx
  src/apiClient.ts
  src/components/Spinner.tsx
  src/index.css
  src/pages/ArenaPage/RankingList.tsx
  src/pages/ArenaPage/RankingListItem.tsx
  src/pages/ArenaPage/index.tsx
  src/pages/ArenaPage/useArenaPage.tsx
  src/pages/AvatarInputPage/index.tsx
  src/types.ts
  yarn.lock
Labels: Extra Large

#20 fix: Base api url
  src/constants.ts
Labels: Extra Small

#21 fix: Fixing various bugs
  src/apiClient.ts
  src/pages/AgentInputPage/index.tsx
  src/pages/ArenaPage/RankingListItem.tsx
Labels: Extra Small

#22 Cache agent, avatar address
  src/pages/AgentInputPage/index.tsx
  src/pages/ArenaPage/index.tsx
  src/pages/AvatarInputPage/index.tsx
Labels: Small

#23 feat: Handle negative pages
  src/pages/ArenaPage/index.tsx
Labels: Extra Small
